import json
import os
import sys
from datetime import datetime

import requests

api_key = os.environ.get("BUTTONDOWN_API_KEY")
commit_message = os.environ.get("COMMIT_MESSAGE", "")

# Read posts from the JSON file generated by hooks.py
posts_json_path = "site/posts.json"

if not os.path.exists(posts_json_path):
    print(f"Error: {posts_json_path} not found. Make sure mkdocs build has run.")
    sys.exit(1)

with open(posts_json_path, "r") as f:
    posts = json.load(f)

if not posts:
    print("No posts found.")
    sys.exit(0)

# Find the most recent date and get all posts with that date
dates = [datetime.fromisoformat(p["date"]) for p in posts if p["date"]]
if not dates:
    print("No posts with dates found.")
    sys.exit(0)

most_recent_date = max(dates)
recent_posts = [
    p
    for p in posts
    if p["date"] and datetime.fromisoformat(p["date"]).date() == most_recent_date.date()
]

# Construct the email body
posts_list = "\n".join([f"- [{p['title']}]({p['url']})" for p in recent_posts])

body = f"""New post{"s" if len(recent_posts) > 1 else ""} published:

{posts_list}
"""

url = "https://api.buttondown.com/v1/emails"
headers = {
    "Authorization": f"Token {api_key}",
    "Content-Type": "application/json",
    "X-Buttondown-Live-Dangerously": "true",  # Confirms you want to send instantly
}
data = {
    "subject": f"New post{'s' if len(recent_posts) > 1 else ''} from patrick's blog",
    "body": body,
    "status": "about_to_send",
}

response = requests.post(url, headers=headers, json=data)

if response.status_code == 201:
    print("Newsletter successfully queued for sending!")
else:
    print(f"Failed to send: {response.text}")
    sys.exit(1)
